name: Auto Terraform Apply on Image Push

on:
  repository_dispatch:
    types: [cloudbuild-image-pushed]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Terraform Code
      uses: actions/checkout@v3

    - name: Authenticate to GCP
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}

    - name: Setup gcloud CLI
      uses: google-github-actions/setup-gcloud@v1
      with:
        version: 'latest'

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.6.6
        cli_config_credentials: false

    - name: Check Terraform Version (verify installation)
      run: |
        which terraform
        terraform version

    - name: Get Image Digest from Artifact Registry
      id: digest
      run: |
        IMAGE="northamerica-northeast2-docker.pkg.dev/bluemind-d6c37/blue-mind-prod-repo-gcp/bluemind-app:${{ github.event.client_payload.sha }}"
        DIGEST=$(gcloud artifacts docker images describe "$IMAGE" --format='value(image_summary.digest)')
        FULL_IMAGE="northamerica-northeast2-docker.pkg.dev/bluemind-d6c37/blue-mind-prod-repo-gcp/bluemind-app@$DIGEST"
        echo "digest=$FULL_IMAGE" >> "$GITHUB_OUTPUT"

    - name: List Terraform Files (debug)
      run: ls -al
      working-directory: ${{ github.workspace }}/Bluemind-cloudrun-terraform

    - name: Terraform Init
      run: terraform init
      working-directory: ${{ github.workspace }}/Bluemind-cloudrun-terraform

    - name: Terraform Plan
      run: terraform plan -var="image_url=${{ steps.digest.outputs.digest }}"
      working-directory: ${{ github.workspace }}/Bluemind-cloudrun-terraform

    - name: Terraform Apply
      run: terraform apply -auto-approve -var="image_url=${{ steps.digest.outputs.digest }}"
      working-directory: ${{ github.workspace }}/Bluemind-cloudrun-terraform

