name: Auto Terraform Apply on Image Push

on:
  repository_dispatch:
    types: [cloudbuild-image-pushed]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Code
      - name: Checkout Terraform Code
        uses: actions/checkout@v3

      # Step 2: Authenticate to GCP
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      # Step 3: Setup gcloud CLI
      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: 'latest'

      # Step 4: Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6
          cli_config_credentials: false

      # Step 5: Check Terraform Version
      - name: Check Terraform Version
        run: |
          which terraform
          terraform version

      # Step 6: Get Image Digest from Artifact Registry
      - name: Get Image Digest
        id: digest
        run: |
          IMAGE="northamerica-northeast2-docker.pkg.dev/bluemind-d6c37/blue-mind-prod-repo-gcp/bluemind-app:${{ github.event.client_payload.sha }}"
          DIGEST=$(gcloud artifacts docker images describe "$IMAGE" --format='value(image_summary.digest)')
          FULL_IMAGE="northamerica-northeast2-docker.pkg.dev/bluemind-d6c37/blue-mind-prod-repo-gcp/bluemind-app@$DIGEST"
          echo "digest=$FULL_IMAGE" >> "$GITHUB_OUTPUT"

      # Step 7: Debug - list Terraform files
      - name: List Terraform Files (debug)
        run: ls -al
        working-directory: ./Bluemind-cloudrun-terraform

      # Step 8: Debug - find *.tf files
      - name: Check for .tf files
        run: find . -name "*.tf"
        working-directory: ./Bluemind-cloudrun-terraform

      # Step 9: Terraform Init
      - name: Terraform Init
        run: terraform -chdir=./Bluemind-cloudrun-terraform init

      # Step 10: Terraform Plan
      - name: Terraform Plan
        run: |
          $TERRAFORM_CLI_PATH/terraform-bin -chdir=./Bluemind-cloudrun-terraform plan \
            -var="image_url=${{ steps.digest.outputs.digest }}" \
            -var="project_id=${{ secrets.PROJECT_ID }}" \
            -var="region=${{ secrets.REGION }}" \
            -var="db_connection_name=${{ secrets.DB_CONNECTION_NAME }}" \
            -var="db_user=${{ secrets.DB_USER }}" \
            -var="db_secret_id=${{ secrets.DB_SECRET_ID }}" \
            -var="db_port=${{ secrets.DB_PORT }}" \
            -var="db_name=${{ secrets.DB_NAME }}" \
            -var="email_user=${{ secrets.EMAIL_USER }}" \
            -var="email_password=${{ secrets.EMAIL_PASSWORD }}" \
            -var="jwt_secret=${{ secrets.JWT_SECRET }}" \
            -var="secret_key=${{ secrets.SECRET_KEY }}" \
            -var="gemini_key=${{ secrets.GEMINI_KEY }}" \
            -var="gcs_bucket_name=${{ secrets.GCS_BUCKET_NAME }}"
        env:
          TERRAFORM_CLI_PATH: /home/runner/work/_temp/5481c919-73e5-42de-9bb1-95a35b27ccca

      # Step 11: Terraform Apply
      - name: Terraform Apply
        run: |
          $TERRAFORM_CLI_PATH/terraform-bin -chdir=./Bluemind-cloudrun-terraform apply -auto-approve \
            -var="image_url=${{ steps.digest.outputs.digest }}" \
            -var="project_id=${{ secrets.PROJECT_ID }}" \
            -var="region=${{ secrets.REGION }}" \
            -var="db_connection_name=${{ secrets.DB_CONNECTION_NAME }}" \
            -var="db_user=${{ secrets.DB_USER }}" \
            -var="db_secret_id=${{ secrets.DB_SECRET_ID }}" \
            -var="db_port=${{ secrets.DB_PORT }}" \
            -var="db_name=${{ secrets.DB_NAME }}" \
            -var="email_user=${{ secrets.EMAIL_USER }}" \
            -var="email_password=${{ secrets.EMAIL_PASSWORD }}" \
            -var="jwt_secret=${{ secrets.JWT_SECRET }}" \
            -var="secret_key=${{ secrets.SECRET_KEY }}" \
            -var="gemini_key=${{ secrets.GEMINI_KEY }}" \
            -var="gcs_bucket_name=${{ secrets.GCS_BUCKET_NAME }}"
        env:
          TERRAFORM_CLI_PATH: /home/runner/work/_temp/5481c919-73e5-42de-9bb1-95a35b27ccca
