name: Terraform Plan on Image Push

on:
  repository_dispatch:
    types: [cloudbuild-image-pushed]

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5 # or your required version

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Terraform Init
        working-directory: ./Bluemind-cloudrun-terraform
        run: terraform init

      - name: Terraform Plan
        working-directory: ./Bluemind-cloudrun-terraform
        run: |
          terraform plan \
            -var="image_url=${{ secrets.IMAGE_URL }}" \
            -var="project_id=${{ secrets.GCP_PROJECT_ID }}" \
            -var="region=${{ secrets.GCP_REGION }}" \
            -var="db_connection_name=${{ secrets.DB_CONNECTION_NAME }}" \
            -var="db_user=${{ secrets.DB_USER }}" \
            -var="db_secret_id=${{ secrets.DB_SECRET_ID }}" \
            -var="db_port=${{ secrets.DB_PORT }}" \
            -var="db_name=${{ secrets.DB_NAME }}" \
            -var="email_user=${{ secrets.EMAIL_USER }}" \
            -var="email_password=${{ secrets.EMAIL_PASSWORD }}" \
            -var="jwt_secret=${{ secrets.JWT_SECRET }}" \
            -var="secret_key=${{ secrets.SECRET_KEY }}" \
            -var="gemini_key=${{ secrets.GEMINI_KEY }}" \
            -var="gcs_bucket_name=${{ secrets.GCS_BUCKET_NAME }}"


      # Step 11: Terraform Apply
      - name: Terraform Apply
        working-directory: ./Bluemind-cloudrun-terraform
        run: |
          terraform apply auto-approve  \
            -var="image_url=${{ steps.digest.outputs.digest }}" \
            -var="project_id=${{ secrets.PROJECT_ID }}" \
            -var="region=${{ secrets.REGION }}" \
            -var="db_connection_name=${{ secrets.DB_CONNECTION_NAME }}" \
            -var="db_user=${{ secrets.DB_USER }}" \
            -var="db_secret_id=${{ secrets.DB_SECRET_ID }}" \
            -var="db_port=${{ secrets.DB_PORT }}" \
            -var="db_name=${{ secrets.DB_NAME }}" \
            -var="email_user=${{ secrets.EMAIL_USER }}" \
            -var="email_password=${{ secrets.EMAIL_PASSWORD }}" \
            -var="jwt_secret=${{ secrets.JWT_SECRET }}" \
            -var="secret_key=${{ secrets.SECRET_KEY }}" \
            -var="gemini_key=${{ secrets.GEMINI_KEY }}" \
            -var="gcs_bucket_name=${{ secrets.GCS_BUCKET_NAME }}"
